---
- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=864000

- include: control.yml

- include: database.yml

- include: webserver.yml

- include: loadbalancer.yml
