---
# handlers file for kubernetes-master
- name: start ntp
  service: name=ntpd enabled=yes state=started

- name: restart ntp
  service: name=ntpd state=restarted

- name: start kube-apiserver
  service: name=kube-apiserver enabled=yes state=started

- name: restart kube-apiserver
  service: name=kube-apiserver state=restarted

- name: start kube-controller-manager
  service: name=kube-controller-manager enabled=yes state=started

- name: restart kube-controller-manager
  service: name=kube-controller-manager state=restarted

- name: start kube-scheduler
  service: name=kube-scheduler enabled=yes state=started

- name: restart kube-scheduler
  service: name=kube-scheduler state=restarted