---
- hosts: loadbalancer
  become: true
  tasks:
    - name: verfiy nginx service
      command: service nginx status
    
    - name: verify nginx is listening on 80
      wait_for: port=80 timeout=1

- hosts: webserver
  become: true
  tasks:
    - name: verfiy apache2 service
      command: service apache2 status

    - name: verify apach2 is listening on 80
      wait_for: port=80 timeout=1


- hosts: database
  become: true
  tasks:
    - name: verfiy mysql service
      command: service mysql status

    - name: verify mysql is listening on 3306
      wait_for: port=3306 timeout=1

